//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regentes.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IConsultaRegistro")]
    public interface IConsultaRegistro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaRegistro/ExisteREG", ReplyAction="http://tempuri.org/IConsultaRegistro/ExisteREGResponse")]
        bool ExisteREG(string CodReg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaRegistro/FecIns", ReplyAction="http://tempuri.org/IConsultaRegistro/FecInsResponse")]
        System.DateTime FecIns(string CodReg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaRegistro/FecVen", ReplyAction="http://tempuri.org/IConsultaRegistro/FecVenResponse")]
        System.DateTime FecVen(string CodReg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaRegistroChannel : Regentes.ServiceReference1.IConsultaRegistro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaRegistroClient : System.ServiceModel.ClientBase<Regentes.ServiceReference1.IConsultaRegistro>, Regentes.ServiceReference1.IConsultaRegistro {
        
        public ConsultaRegistroClient() {
        }
        
        public ConsultaRegistroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaRegistroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaRegistroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaRegistroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ExisteREG(string CodReg) {
            return base.Channel.ExisteREG(CodReg);
        }
        
        public System.DateTime FecIns(string CodReg) {
            return base.Channel.FecIns(CodReg);
        }
        
        public System.DateTime FecVen(string CodReg) {
            return base.Channel.FecVen(CodReg);
        }
    }
}
